Options to set a winner value.

diff --git a/2048 b/2048
--- a/2048
+++ b/2048
@@ -3,6 +3,7 @@
 declare -A board
 
 clear=no
+limit=0
 
 boardRows=4
 boardColumns=4
@@ -218,13 +219,30 @@ function checkNoMoreMoves() {
 	:
 }
 
+function checkLimit() {
+	if [ $limit -le 0 ]; then
+		return 1
+	fi
+	for i in $(seq 1 $boardRows); do
+		for j in $(seq 1 $boardColumns); do
+			if [ "${board[$i,$j]}" != " " ]; then
+				if [ ${board[$i,$j]} -ge $limit ]; then
+					return 0
+				fi
+			fi
+		done
+	done
+	return 1
+}
+
 function showCLIHelp() {
 	echo "2048 Game written in BASH"
 	echo "Diego Lago González <diego.lago.gonzalez@gmail.com>"
 	echo "Usage: $(basename $0) [options]"
 	echo "Options:"
-	echo " -c   Clear the screen."
-	echo " -h   Show this help and exit."
+	echo " -c       Clear the screen on every movement."
+	echo " -l <val> Specifies a maximun game value (where you win)."
+	echo " -h       Show this help and exit."
 	echo
 	echo "During game:"
 	showHelp nocredits
@@ -300,13 +318,24 @@ function printBoard() {
 }
 
 function processOptions() {
-	while getopts ":ch" opt; do
+	while getopts ":cl:h" opt; do
 		case "$opt" in
 			c)
 				clear=yes
 			;;
+			l)
+				limit=$OPTARG
+			;;
 			h)
 				showCLIHelp
+			;;
+			\?)
+				echo "ERROR: Invalid option: -$OPTARG" 1>&2
+				exit 1
+			;;
+			:)
+				echo "ERROR: Option -$OPTARG requires a value." 1>&2
+				exit 1
 			;;
 		esac
 	done
@@ -324,6 +353,14 @@ function main() {
 			newBoardRandomValue
 		fi
 		checkNoMoreMoves
+		if checkLimit; then
+			printBoard
+			echo
+			echo " *** Congratulations! You Win! ***"
+			echo
+			read -n1 -p "Press any key to continue..."
+			echo
+		fi
 	done
 }
 
